// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ai_gallery_organizer/core/models/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BoardAdapter());
    registerAdapter(ScreenshotCategoryAdapter());
    registerAdapter(ScreenshotEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BoardAdapter());
    registerAdapter(ScreenshotCategoryAdapter());
    registerAdapter(ScreenshotEntryAdapter());
  }
}
